quotes = [
    # Discipline (1-60)
    "Discipline is choosing your future over your comfort.",
    "Success begins the moment excuses end.",
    "Small disciplined actions create extraordinary results.",
    "Your future self will thank you for today's effort.",
    "Every workout is a promise you keep to yourself.",
    "Progress is built one day at a time.",
    "Consistency is stronger than motivation.",
    "Your body reflects your daily habits.",
    "Dream big. Start small. Stay consistent.",
    "One healthy choice today creates a better tomorrow.",
    "Discipline begins where excuses end.",
    "Every promise you keep to yourself makes you stronger.",
    "Your habits decide your future long before your results do.",
    "Don't wait for the perfect day. Make today count.",
    "A disciplined mind creates an unstoppable life.",
    "Great achievements are built from ordinary daily actions.",
    "The hardest step is showing up. Take it anyway.",
    "Success doesn't ask for talent first; it asks for consistency.",
    "Each disciplined decision is a vote for the person you want to become.",
    "Today's effort is tomorrow's confidence.",
    "The life you want begins with the habits you build today.",
    "Discipline is the bridge between dreams and reality.",
    "Every sunrise gives you another chance to improve.",
    "Choose progress over excuses, every single time.",
    "Winning starts with the courage to begin.",
    "One disciplined day may seem small, but years are built from days.",
    "Keep showing up. Greatness notices consistency.",
    "Every challenge is another opportunity to grow stronger.",
    "Train your mind first, and your body will follow.",
    "A single step forward is still progress.",
    "Discipline is doing the right thing even when nobody is watching.",
    "Don't count the days; make each day count.",
    "Success is hidden inside your daily routine.",
    "Comfort is temporary, but discipline lasts a lifetime.",
    "The strongest version of you is created one choice at a time.",
    "You become what you repeatedly choose to do.",
    "There is no shortcut to a stronger tomorrow.",
    "Stay patient. Strong habits take time to grow.",
    "Focus on becoming better, not becoming perfect.",
    "Every disciplined action writes a better future.",
    "The first victory of the day is choosing not to quit.",
    "Every disciplined morning creates a successful evening.",
    "Your future is listening to the choices you make today.",
    "Stay committed long enough for your efforts to surprise you.",
    "The strongest people master themselves before anything else.",
    "Small improvements repeated daily become extraordinary results.",
    "Your limits exist only until you challenge them.",
    "One more step. One more rep. One more chance to grow.",
    "A disciplined life is built from disciplined moments.",
    "The best investment you can make is in yourself.",
    "Your determination speaks louder than your excuses.",
    "Today's discipline is tomorrow's freedom.",
    "Don't wait to feel ready. Start, and confidence will follow.",
    "Strength begins with the decision to keep moving forward.",
    "Success is built every day, not overnight.",
    "Focus on progress, not comparison.",
    "Discipline turns a difficult journey into a lasting habit.",
    "Every challenge you overcome becomes part of your strength.",
    #Fitness (61-120)
    "Believe in your effort even before you see the results.",
    "The person you become is shaped by the choices you repeat.",
    "Your body is your lifelong teammate. Treat it with care.",
    "Every workout is a step toward a healthier you.",
    "Strong bodies are built through patient consistency.",
    "Move today so your future self can thank you.",
    "Fitness is a journey, not a race.",
    "Every drop of sweat is proof of your determination.",
    "A healthy body gives strength to a focused mind.",
    "Train with purpose, recover with patience.",
    "Your muscles grow when your excuses shrink.",
    "Every repetition makes you stronger than yesterday.",
    "Fitness is not about perfection; it is about progress.",
    "The hardest workout is the one you never start.",
    "Exercise is a celebration of what your body can do.",
    "A stronger body begins with one decision to move.",
    "Your greatest competition is the person you were yesterday.",
    "Stay active today to enjoy a healthier tomorrow.",
    "Train your body with respect, not punishment.",
    "The effort you invest today becomes the strength you carry tomorrow.",
    "A healthy lifestyle begins with one active choice.",
    "Your body grows stronger with every challenge you accept.",
    "Movement is medicine for both the body and the mind.",
    "Every workout is a gift to your future self.",
    "Train consistently and let the results speak for themselves.",
    "The road to fitness is paved with daily effort.",
    "Strength is built one repetition at a time.",
    "Every exercise brings you closer to your goals.",
    "Take care of your body; it carries your dreams.",
    "Fitness rewards patience and persistence.",
    "A stronger body creates a stronger mindset.",
    "Small workouts done consistently create big transformations.",
    "Your health is your greatest wealth.",
    "Every active day is a successful day.",
    "The best time to exercise is the time you decide to begin.",
    "Push yourself with purpose, not pressure.",
    "Healthy habits outlast temporary motivation.",
    "Stay committed even when progress feels slow.",
    "Your effort today shapes your energy tomorrow.",
    "Fitness is built through determination, not shortcuts.",
    "Your body becomes stronger every time you refuse to give up.",
    "Every workout is another step toward a healthier future.",
    "Take care of your body today, and it will take care of you tomorrow.",
    "Strong habits create strong bodies.",
    "Fitness is earned through consistency, not luck.",
    "Every challenge you complete adds to your strength.",
    "Your health deserves your time and effort.",
    "Keep moving, even if the steps are small.",
    "A fit body begins with a determined mind.",
    "Every workout is an act of self-respect.",
    "Strength grows when comfort ends.",
    "Healthy choices today become healthy habits tomorrow.",
    "Success in fitness starts with showing up.",
    "Exercise because your body deserves the best.",
    "Stay active, stay healthy, stay unstoppable.",
    "Every goal is reached one workout at a time.",
    "Discipline fuels the body, and determination drives the journey.",
    "Your greatest strength is your commitment to never stop improving.",
    "A healthier life begins with the decision you make today.",
    #Health (121-180)
    "Good health is built through small daily choices.",
    "A healthy body begins with a healthy routine.",
    "Drink water today; your body will thank you tomorrow.",
    "Sleep is your body's reset button, not a luxury.",
    "Choose foods that nourish your future.",
    "Healthy habits create a healthy life.",
    "Every balanced meal is an investment in yourself.",
    "Rest is part of progress, not a break from it.",
    "Take care of your body—it works for you every day.",
    "Health grows through consistency, not perfection.",
    "Listen to your body before it asks you to slow down.",
    "Every glass of water fuels your journey.",
    "Good nutrition gives strength to every dream.",
    "Protect your health as you would protect your future.",
    "Eat with purpose, not just with hunger.",
    "Wellness starts from within.",
    "Small healthy habits become lifelong rewards.",
    "A peaceful mind supports a healthy body.",
    "Your energy reflects the care you give yourself.",
    "Rest today so you can rise stronger tomorrow.",
    "Health is your greatest lifelong investment.",
    "Fuel your body with kindness and care.",
    "Strong health builds strong confidence.",
    "Recovery is where growth truly begins.",
    "Healthy mornings create productive days.",
    "Make wellness your daily priority.",
    "The best medicine is prevention through healthy habits.",
    "Every nutritious meal is an act of self-respect.",
    "A calm mind creates a healthier life.",
    "Health is earned one habit at a time.",
    "Fresh air is food for the soul.",
    "Healthy living is a lifelong adventure.",
    "Small improvements create lasting wellness.",
    "Balance is the secret to lasting health.",
    "Every hour of good sleep is an investment in tomorrow.",
    "Healthy routines build extraordinary lives.",
    "Your body deserves patience and respect.",
    "Health is not a destination; it is a lifestyle.",
    "Your future depends on the habits you build today.",
    "Choose foods that energize your dreams.",
    "Every healthy decision shapes a healthier tomorrow.",
    "Wellness begins with self-care.",
    "Your health is the foundation of every success.",
    "Stay active, stay hydrated, stay grateful.",
    "Treat your body as your lifelong companion.",
    "Strong health begins with simple choices.",
    "Consistency in health brings lifelong rewards.",
    "A healthy mind inspires a healthy body.",
    "Every sunrise is another chance to care for yourself.",
    "Wellness is built through love, not pressure.",
    "The healthiest choice is often the simplest one.",
    "Your greatest wealth will always be your health.",
    #Confidence(Day 181–240)
    "Confidence begins the moment you believe in yourself.",
    "Your voice deserves to be heard.",
    "Stand tall, even when you feel uncertain.",
    "Believe in your abilities before expecting others to.",
    "Every challenge builds your confidence.",
    "Your uniqueness is your greatest strength.",
    "Do not fear mistakes; fear never trying.",
    "The courage to begin is the first sign of confidence.",
    "Trust yourself—you have overcome difficult days before.",
    "Every small victory strengthens your self-belief.",
    "Confidence grows through action, not waiting.",
    "Walk with purpose and let your actions speak.",
    "You are stronger than your doubts.",
    "Every obstacle is another chance to prove your strength.",
    "Speak with kindness, but never underestimate your worth.",
    "Believe in your journey, even when others cannot see it.",
    "Confidence is built by keeping promises to yourself.",
    "Do not compare your beginning to someone else's success.",
    "Be proud of how far you have already come.",
    "Your greatest strength is believing that you can improve.",
    "Confidence is earned one brave decision at a time.",
    "Be fearless in learning and humble in success.",
    "The only approval you truly need is your own.",
    "Every new experience makes you stronger.",
    "You are capable of more than you realize.",
    "Believe in your progress, even when it is slow.",
    "Face your fears; they are stepping stones to growth.",
    "True confidence comes from preparation.",
    "Every question you ask is a step toward wisdom.",
    "Choose courage over comfort every day.",
    "You become confident by doing, not by waiting.",
    "Never let fear decide your future.",
    "Your confidence inspires those around you.",
    "Be proud of your effort, not just your results.",
    "Strength begins when self-doubt ends.",
    "Every challenge prepares you for something greater.",
    "Walk into every room believing you belong there.",
    "The greatest competition is yesterday's version of you.",
    "You are enough as you are, and capable of becoming even better.",
    "Confidence shines brightest through kindness.",
    "Stand firm in your values and let your actions speak.",
    "Every setback is another lesson in courage.",
    "Trust the process and trust yourself.",
    "The more you practice, the more confident you become.",
    "Your potential is greater than your fears.",
    "Do not hide your talents—share them with the world.",
    "Confidence grows when you step outside your comfort zone.",
    "Your attitude shapes your confidence.",
    "Success follows those who believe they can improve.",
    "Face today with courage and tomorrow with pride.",
    "Be the reason someone believes in themselves today.",
    "Never apologize for chasing your dreams.",
    "Confidence is quiet; it doesn't need to prove itself.",
    "Every day is another opportunity to become your best self.",
    "Choose faith in yourself over fear of failure.",
    "The strongest people keep moving despite uncertainty.",
    "Speak positively to yourself—you are always listening.",
    "Confidence is built through consistent effort.",
    "Believe in the person you are becoming.",
    "A confident heart can achieve extraordinary things.",
    #Success (60)
    "Success is built one disciplined day at a time.",
    "Every great achievement begins with a single decision.",
    "Your future rewards today's effort.",
    "Dream big, but work even bigger.",
    "Success belongs to those who never stop learning.",
    "Every step forward is a success worth celebrating.",
    "Patience and persistence create lasting success.",
    "Your habits shape your destiny.",
    "Success grows where consistency lives.",
    "Small victories lead to extraordinary achievements.",
    "The road to success is paved with determination.",
    "Focus on progress, not applause.",
    "Hard work always leaves its mark.",
    "Success begins with believing you can improve.",
    "The best investment is the effort you put into yourself.",
    "Keep moving forward, even when progress is slow.",
    "Success is earned before it is seen.",
    "Every challenge prepares you for greater opportunities.",
    "Stay committed to your goals.",
    "Your effort today becomes tomorrow's achievement.",
    "Success is a collection of ordinary days done well.",
    "Learn something valuable every single day.",
    "Great goals require great commitment.",
    "Every setback is another lesson in disguise.",
    "The journey matters as much as the destination.",
    "Work quietly and let your results speak.",
    "Discipline creates opportunities that luck never could.",
    "The strongest leaders never stop growing.",
    "Success follows those who refuse to quit.",
    "Keep your purpose stronger than your excuses.",
    "Your actions reveal your priorities.",
    "Every sunrise is a fresh opportunity to succeed.",
    "The best version of yourself is still ahead.",
    "Stay humble while chasing greatness.",
    "Your greatest competition is yesterday's performance.",
    "Be consistent even when nobody notices.",
    "Great achievements require ordinary discipline.",
    "Every goal begins with one courageous step.",
    "Do not fear failure; fear giving up.",
    "Keep your vision clear and your actions steady.",
    "Success belongs to those who prepare for it.",
    "Your future depends on today's discipline.",
    "Great things take time to grow.",
    "Never stop improving yourself.",
    "Every accomplishment starts with action.",
    "The climb is difficult because the view is worth it.",
    "Your determination defines your destination.",
    "Stay focused on what truly matters.",
    "Every challenge hides an opportunity.",
    "Believe in the work you do each day.",
    "Keep learning, keep growing, keep moving.",
    "One determined heart can achieve extraordinary things.",
    "Today's discipline becomes tomorrow's success.",
    "The journey to success starts within.",
    "Success is not luck; it is preparation meeting opportunity.",
    "Your greatest achievement is becoming your best self.",
    # self growth(65)
    "Every day is another opportunity to become a better version of yourself.",
    "Growth begins the moment you choose to learn.",
    "Be patient with yourself; meaningful change takes time.",
    "Small improvements every day create extraordinary lives.",
    "Your mindset shapes your tomorrow.",
    "Never stop learning because life never stops teaching.",
    "Kindness is a strength, not a weakness.",
    "Celebrate your progress, no matter how small.",
    "Every experience teaches something valuable.",
    "Your greatest project will always be yourself.",
    "Choose gratitude before comparison.",
    "Be proud of your journey, not just your destination.",
    "Growth happens outside your comfort zone.",
    "Learn from yesterday and build a better today.",
    "Your attitude decides your direction.",
    "Believe that every new day holds new possibilities.",
    "Stay curious, stay humble, stay growing.",
    "Every lesson learned becomes tomorrow's wisdom.",
    "Your future begins with today's mindset.",
    "Gratitude turns ordinary moments into meaningful memories.",
    "Invest time in becoming the person you admire.",
    "Your character is built by your daily choices.",
    "Learn to enjoy the journey as much as the destination.",
    "True growth begins with self-awareness.",
    "Every challenge helps you discover new strengths.",
    "Take time to appreciate how far you've come.",
    "Success means little without inner peace.",
    "Forgive yourself and keep moving forward.",
    "The best teacher is experience combined with reflection.",
    "A peaceful mind creates a meaningful life.",
    "Every kind word has the power to change someone's day.",
    "Choose understanding before judgment.",
    "Growth is not about being perfect; it's about improving.",
    "Your kindness leaves a lasting legacy.",
    "A grateful heart sees opportunities everywhere.",
    "Believe in the power of small daily improvements.",
    "The greatest victory is mastering yourself.",
    "Keep an open mind and a humble heart.",
    "Every sunrise is a reminder that new beginnings are possible.",
    "The person you become matters more than what you achieve.",
    "Never stop believing in your ability to grow.",
    "Learn, adapt, and keep moving forward.",
    "Inner strength grows through quiet perseverance.",
    "Respect yourself enough to choose what helps you grow.",
    "Growth begins with one honest decision.",
    "The best investment is becoming a better human being.",
    "Be thankful for every lesson life offers.",
    "Your journey is unique—walk it with confidence.",
    "Choose peace over unnecessary worry.",
    "Every moment is a chance to start again.",
    "The future belongs to those who keep learning.",
    "Your greatest strength is your willingness to improve.",
    "Happiness grows where gratitude lives.",
    "Become someone your future self will admire.",
    "Live with purpose, act with kindness, and grow with patience.",
    "The best version of you is created one day at a time.",
    "Stay true to your values, even when no one is watching.",
    "Growth never ends, and neither does your potential.",
    "Mission Complete. You didn't become stronger because of one perfect day. You became stronger because you chose to return, learn, and grow every single day. Tomorrow is another opportunity to become your best self."
]
print(len(quotes))
